version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.2
    env_file:
      - .env
    environment:
      - PG_DATA:/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8080:8080
      - 9229:9229
    depends_on:
      - db
    restart: always
volumes:
  pgdata: